### ISSUE TITLE
4 bit quantization support on torch XLA?

### ISSUE THREAD

**Issue by Locutusque** [pytorch/ao#1022]
Does this library support 4 bit quantization on TPUs (XLA)?

**Comment by msaroufim** [comment]
So, the default way we generate kernels for torchao is via torch.compile and torchinductor. For 4 bit weight only quantization we specifically use a cuda kernel that was merged upstream in pytorch.

We are as a project super open to more hardware vendors but I'm not sure what the right integration story is: do we merge custom XLA kernels? Do we instead of leveraging inductor make sure the backend is configurable and use something else? @shauheen do you have any advice on what to do here? I'm happy to poke around and see if things just work with a different torch.compile backend if I could get some help setting up a TPU in CI

**Comment by lsy323** [comment]
Hello @Locutusque, torch ao doesn't support XLA backend now, but there is ongoing effort to enable torchao for TPU backends.

PyTorch/XLA have w4a16 blockwise kernels available as a custom torch op in PyTorch/XLA (More details [here](https://github.com/pytorch/xla/blob/master/docs/quantized_ops.md)). Quantized custom op [here](https://github.com/pytorch/xla/blob/master/torch_xla/experimental/xla_quantized_matmul.py#L78-L101). If you have the quantized weight and want to deploy on TPU, replace the original linear layer with the w4a16 op in your model code. One thing to note is the layout of the int4 weights, instead of packing into int32, the format is expected to store int4 values in int8 container without packing, the packing we be handled while we transfer the weights to device automatically.

Please feel free to try out the w4a16 kernel on TPU and open an issue under [PyTorch/XLA](https://github.com/pytorch/xla), thanks!
