### ISSUE TITLE
Improvement ideas for `hf_eval.py`

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/ao#332]
When I tried out `scripts/hf_eval.py`, I faced some problems (with 16GB VRAM GPU):

1. OOM when loading original BF16 Llama3-8B model.
    - Workaround: load to CPU first, do quantization on CPU, and transfer to CUDA -> perhaps we should add `--quantize_on_cpu` flag (or something similar)? Quantize on CPU is slower than CUDA, so we probably don't want quantize on CPU being the default.
    - For typically home PCs with 16GB RAM, even loading the original model to CPU RAM is not so ideal. The best is if we can do (1) instantiate the model with "meta" device (2) quantize the "meta" model (so that the weight is in quantized shape) (3) memory-map state dict -> no RAM usage (4) load each weight from memory-map state dict to CPU/GPU and quantize one at a time. This probably cannot be implemented cleanly since we don't have access to internal of `AutoModelForCausalLM.from_pretrained()`.
    - This problem should be applicable for using a large model with torchao in general too, not just for `hf_eval.py`
2. We might want to expose more flags to `HFLM`, for example `batch_size`, `max_length`.
    - `batch_size` can help speed up inference for some tasks, like `hellaswag`
    - On my GPU, I got OOM with Llama3-8B even with int4wo when evaluating on wikitext, probably because (1) Llama3 has huge vocab size and (2) wikitext has very long text -> use max context length for Llama3-8B. When evaluating Llama2-7B w/ int4wo on wikitext, I didn't face OOM. -> useful to limit `max_length`
3. Other misc stuff: change `--task_list` to `--tasks` to align with lm_eval CLI; `--device` flag is currently not used (but I don't think anyone will do LLM eval on CPU anyway?)

**Comment by HDCharles** [comment]
updated:

https://github.com/pytorch/ao/pull/342/files

1a) we can do that for int8 but not int4 (there's an alternative cpu kernel with an alternative packing method which is used automatically when the tensor-to-quantize is on cpu). There's some work going on in the background to clean that up but until then int4 has to be quantized on cuda.

1b) We don't have that kind of workflow implemented anywhere and as you mentioned we don't have a good way to do it with the hf models. Our assumption is that generally if you can't fit the model on cpu then you're probably not in this arena. Not sure if thats a valid assumption though. 

 2) added these, note max_length greatly impacts evaluation accuracy which is why we normally leave it as is.
 
 3) fixed this
