### ISSUE TITLE
Question RE AO MX formats

### ISSUE THREAD

**Issue by tsengalb99** [pytorch/ao#750]
I noticed the [MX readme](https://github.com/pytorch/ao/tree/main/torchao/prototype/mx_formats) has this line: "we match bitwise to other implementations of the OCP MX spec (code not in this repo), with a couple of edge cases left to resolve." Is there a list of edge cases where AO does not match reference implementations? Also, is https://github.com/microsoft/microxcaling the reference implementation AO is trying to match or something else?

**Comment by tsengalb99** [comment]
I'm also noticing that compiling `MXTensor.to_mx` on torch 2.4.0 doesn't seem to make it go any faster. Quantizing a 4k x 4k tensor to MXFP4 with to_mx takes much longer than the times reported in https://gist.github.com/vkuzo/83656e4a74777cfc0915de6b27be1ff6.

**Comment by vkuzo** [comment]
Hi @tsengalb99 , here is the code we used internally to compare to microxcaling: https://gist.github.com/vkuzo/7bf9a101dd64817c603c6a8417400eda .

In the code above, there is a single instance of `pytest.skip`, where the numerics do match for very small numbers initialized with `x = torch.distributions.uniform.Uniform(0, 1e-38).sample([size])`.  I just haven't had time to look into the discrepancy, but it would be great if someone helped out with this.

> I'm also noticing that compiling MXTensor.to_mx on torch 2.4.0 doesn't seem to make it go any faster

Sure, I have a couple of thoughts here:
1. this code is early prototype without any expectation of high performance until the NVIDIA hardware with MX support is officialy released, and we plan to do performance optimizations after we know the exact specs and provided intrinsic functions of the MX support on the released hardware, so we know where the bottlenecks are.
2. I would use PT nightly instead of 2.4 for more up to date numbers.

**Comment by vkuzo** [comment]
please feel free to reopen if needed!
