### ISSUE TITLE
Plans for 8da4w quantization

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/ao#883]
Hi,

From #430, it seems that 8da4w is primarily for Executorch, and is set to be deprecated. Please advise if there are any plans to enable it for CUDA & CPU as well, such that int4 weights could be converted to int8 just before computation?

Thanks!

cc @jerryzh168

**Comment by Xia-Weiwen** [comment]
Hi @jerryzh168 I saw your pointer here:
https://github.com/pytorch/ao/tree/main/torchao/quantization#to-be-deprecated-a8w8-dynamic-quantization
However, we need 8da4w for CPU and XPU and we don't want it deprecated. May I know any concern from your side? Thanks

CC. @jgong5 @leslie-fang-intel

**Comment by jerryzh168** [comment]
this is used for executorch before, but it seems that we have people adding kernels here: https://github.com/pytorch/ao/pull/880. we are open to adding kernels for this

**Comment by Xia-Weiwen** [comment]
> this is used for executorch before, but it seems that we have people adding kernels here: #880. we are open to adding kernels for this

Got it. Thanks for the clarification!

**Comment by jerryzh168** [comment]
@Xia-Weiwen that link is talking about the quantizer API since we are updating to the `quantize_` API, we'll be using something like https://github.com/pytorch/ao/tree/main/torchao/quantization#a8w8-dynamic-quantization but with https://github.com/pytorch/ao/blob/8236a874479a9a9168e584c81dda8707f4c41006/torchao/quantization/quant_api.py#L83 as the second argument.

**Comment by Xia-Weiwen** [comment]
Thanks for the pointers!

**Comment by sanchitintel** [comment]
Thanks for clarifying, @jerryzh168!
